### ISSUE TITLE
Using this addon breaks the ExtendedGrid component

### ISSUE THREAD

**Issue by a-schild** [FlowingCode/GridHelpers#23]
https://github.com/vaadin-component-factory/enhanced-grid-flow/issues/17

https://github.com/vaadin-component-factory/enhanced-grid-flow

Using setSelectionColumnFrozen() or any of the other helpers results in this error

Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "str" is null
	at java.base/java.lang.String.concat(String.java:1969)
	at com.vaadin.componentfactory.enhancedgrid.EnhancedGrid.lambda$setClassNameGenerator$aecf28e2$1(EnhancedGrid.java:207)
	at com.vaadin.flow.component.grid.Grid.generateStyleData(Grid.java:3828)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47)
	at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:1436)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)

**Comment by javier-godoy** [comment]
Sorry for the late response, I had reviewed this one and forgot to answer.

It is a bug in `EnhancedGrid` [(here)](https://github.com/vaadin-component-factory/enhanced-grid-flow/blob/ec93f58793970eec25a0aed02cb79ec4b4d1f716/enhanced-grid-flow/src/main/java/com/vaadin/componentfactory/enhancedgrid/EnhancedGrid.java#L207), because the [documentation](https://github.com/vaadin/flow-components/blob/585e99c63d29ca8b627b2b50ab5b7cc1282d3e72/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1003-L1005) of `Grid.setClassNameGenerator` specifies that:
> returning `null` from the generator results in no custom class name being set.

GridHelpers internally configures a generator that can return null. 
https://github.com/FlowingCode/GridHelpers/blob/dfe8ccd4834ac4233b3259ea124be9e752660728/src/main/java/com/flowingcode/vaadin/addons/gridhelpers/GridHelperClassNameGenerator.java#L66
