### ISSUE TITLE
getHeader is not compatible with Vaadin 24

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/GridHelpers#36]
`GridHelper.getHeader` calls `AbstractColumn.getHeaderRenderer()`, which does not exist in Vaadin 24. However, reflection will not be needed for Vaadin 23.2+ after #33 is fixed.

```
java.lang.NoSuchMethodException: com.vaadin.flow.component.grid.AbstractColumn.getHeaderRenderer()
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675) ~[na:na]
        at com.flowingcode.vaadin.addons.gridhelpers.HeaderFooterGridHelper.getHeaderRenderer(HeaderFooterGridHelper.java:33) ~[grid-helpers-0.3.2-SNAPSHOT.jar!/:0.3.2-SNAPSHOT]
```        
https://github.com/FlowingCode/GridHelpers/blob/9d9afa58fad582660dabfb345fbf41887344d9ce/src/main/java/com/flowingcode/vaadin/addons/gridhelpers/HeaderFooterGridHelper.java#L33

**Comment by javier-godoy** [comment]
Closed in #46
