### ISSUE TITLE
Empty grid in Vaadin 24 demo

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/GridHelpers#47]
The "all features" demo renders an empty grid in Vaadin 24 (but the addon seems otherwise operational)

![image](https://user-images.githubusercontent.com/11554739/207136963-ad498f86-84d8-4f1d-ba22-b4ca3428b6cc.png)

The following error is logged in the browser console:
```
vaadin-1-703b1d3edd0227d45d5e.cache.js:8891 Uncaught TypeError: Cannot read properties of null (reading 'parentElement')
    at vaadin-3-40fe6abd48cf08f05624.cache.js:691:861
    at NodeList.forEach (<anonymous>)
    at Q.<anonymous> (vaadin-3-40fe6abd48cf08f05624.cache.js:691:778)
    at Q._resizeHandler (vaadin-1-703b1d3edd0227d45d5e.cache.js:2853:10117)
    at Q._renderColumnTree (vaadin-1-703b1d3edd0227d45d5e.cache.js:2853:9056)
    at Q._columnTreeChanged (vaadin-1-703b1d3edd0227d45d5e.cache.js:2853:7568)
    at Object.$ [as fn] (vaadin-1-703b1d3edd0227d45d5e.cache.js:4938:6225)
    at x (vaadin-1-703b1d3edd0227d45d5e.cache.js:4938:621)
    at Q._propertiesChanged (vaadin-1-703b1d3edd0227d45d5e.cache.js:4938:12149)
    at t._propertiesChanged (vaadin-6-6453354526f740e26f2e.cache.js:1:121425)
    at Q._flushProperties (vaadin-1-703b1d3edd0227d45d5e.cache.js:4958:2563)
    at Q._invalidateProperties (vaadin-1-703b1d3edd0227d45d5e.cache.js:4938:11116)
    at Object.defineProperty.set (vaadin-1-703b1d3edd0227d45d5e.cache.js:4958:973)
    at Q._updateColumnTree (vaadin-1-703b1d3edd0227d45d5e.cache.js:2786:239)
    at Q.<anonymous> (vaadin-1-703b1d3edd0227d45d5e.cache.js:2786:577)
    at a.flush (vaadin-1-703b1d3edd0227d45d5e.cache.js:572:2490)
    at vaadin-1-703b1d3edd0227d45d5e.cache.js:572:1483
    at MutationObserver.<anonymous> (vaadin-1-703b1d3edd0227d45d5e.cache.js:688:162)
 ```

**Comment by javier-godoy** [comment]
A minimum example that reproduces the issue is:
```
    setSizeFull();
    Grid<Integer> grid = new Grid<>();
    grid.addColumn(x -> x).setHeader("col1");
    grid.addColumn(x -> x).setHeader("col2");
    grid.setItems(1, 2, 3);

    grid.getElement().getStyle().set("flex-grow", "1");

    SplitLayout split = new SplitLayout(grid, new Div());
    add(split);

    GridHelper.isSelectOnClick(grid);
    Component toolBar = new Span("HELLO");

    grid.appendFooterRow();
    grid.getElement().getThemeList().add("hide-first-footer");
    FooterRow fr = grid.appendFooterRow();
    FooterCell fc = fr.join(grid.getColumns().toArray(new Grid.Column[0]));
    toolBar.getElement().setAttribute("fcGh-footer", true);
    fc.setComponent(toolBar);
```

**Comment by javier-godoy** [comment]
https://github.com/FlowingCode/GridHelpers/blob/fc2310146acf230a88d123c2256b930328d5d256/src/main/resources/META-INF/frontend/fcGridHelper/connector.js#L46-L50

V23: the `[fcgh-footer]` is slotted inside of a flow-component-renderer
![image](https://user-images.githubusercontent.com/11554739/208730827-7875b93c-49e7-4dcc-9923-5c37b6681b7b.png)

V24
![image](https://user-images.githubusercontent.com/11554739/208730873-8ca34e01-cbc2-4fc2-9fb2-23ca0b684031.png)
