### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot join less than 2 cells error when adding footer to grid

### ISSUE THREAD

**Issue by wegerv** [FlowingCode/GridHelpers#90]
I'm using GridHelpers 1.1.1. and Vaadin 24.1.4.

I add a footer to a grid with just one column. The error (java.lang.IllegalArgumentException: Cannot join less than 2 cells) comes from FooterToolbarGridHelper.java:28 (from stacktrace) .

**Comment by paodb** [comment]
Was able to reproduce it by adding only one column to the [demo example](https://github.com/FlowingCode/GridHelpers/blob/c97009ea81e54f3d7168169b9cac3290f8cded27/src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AddToolbarFooterDemo.java#L39).

**Comment by paodb** [comment]
Stack trace: 

```
Caused by: java.lang.IllegalArgumentException: Cannot join less than 2 cells
at com.vaadin.flow.component.grid.AbstractRow.join(AbstractRow.java:276)
at com.vaadin.flow.component.grid.FooterRow.join(FooterRow.java:86)
at com.vaadin.flow.component.grid.FooterRow.join(FooterRow.java:30)
at com.vaadin.flow.component.grid.AbstractRow.join(AbstractRow.java:215)
at com.vaadin.flow.component.grid.FooterRow.join(FooterRow.java:30)
at com.flowingcode.vaadin.addons.gridhelpers.FooterToolbarGridHelper.setFooterToolbar(FooterToolbarGridHelper.java:28)
at com.flowingcode.vaadin.addons.gridhelpers.GridHelper.addToolbarFooter(GridHelper.java:346)
at com.flowingcode.vaadin.addons.gridhelpers.AddToolbarFooterDemo.<init>(AddToolbarFooterDemo.java:53)
... 72 more
```
